pipeline {
    agent {
        dockerfile {
            dir 'server'
        }
    };
    stages {
        stage ("docker") {
            steps {
                node {
                    def customImg = docker.build("tal19987/imdb:python-${env.BUILD_ID}", "-f server/Dockerfile")
                    customImg.push()
                }
            }
        }
    }
}