pipeline {
    agent {dockerfile true};
        stages {
            stage('Docker') {
                steps {
                    dir("./server/") {
                        sh "in container"
                        sh "hostname"
                }
            }
        }
    }
}