pipeline {
    agent {dockerfile true};
    dir("./server/") {
        stages {
            stage('Docker') {
                steps {
                    sh "in container"
                    sh "hostname"
                }
            }
        }
    }
}